import Header from "./Header/Header"
import Footer from "./Footer/Footer"
import Head from 'next/head'
import FooterMobile from "./Footer/FooterMobile"
import React, {useState} from "react"

export default function Layout({ children }) {
    const [navSelected, setNavSelected] = useState('home')
    const [isOpen, setIsOpen] = useState(false)

    const capitalizeTabName = navSelected.charAt(0).toUpperCase() + navSelected.slice(1)

    return (
        <div className="min-h-screen	flex flex-col">  
              <Head>
                <title className="capitalize">{capitalizeTabName}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="/favicon/favicon.ico" />
            </Head>
          
                <Header
                    navSelected={navSelected}
                    setNavSelected={setNavSelected}
                    isOpen={isOpen}
                    setIsOpen={setIsOpen}
                />
                <main  
                    className="flex-grow" 
                    // setNavSelected={setNavSelected}
                    >{children}
                </main>
                <Footer 
                   setNavSelected={setNavSelected}
                />
                <FooterMobile
                    setNavSelected={setNavSelected}
                    navSelected={navSelected}

                />
      </div>
      
    )
  }